# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://socprivconfresearch.org
title: Society for Privacy and Confidentiality Research
email: your-email@domain.com
author: SPCR
description: > # "Write an awesome description for your new site here. 
  The Society for Privacy and Confidentiality Resarch exists to support the Journal of Privacy and Confidentiality and connected activties.
copyright: 'Copyright &copy; 2024 Society for Privacy and Confidentiality Research. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created from <a href="https://github.com/swcool">swcool</a>.'
logo: /img/Logo_5.jpg


# ----------------------- #
#  Stuff about the society#
# ----------------------- #

president:  TBD
treasurer: TBD 
secretary: Alan Karr (acting)

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: journal
    icon: newspaper
    url: https://journalprivacyconfidentiality.org/
  - title: github
    icon: github
    url: https://github.com/journalprivacyconfidentiality/
