# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://socprivconfresearch.org
title: Society for Privacy and Confidentiality Research
email: spcr@journalprivacyconfidentiality.org
author: SPCR
description: > # "Write an awesome description for your new site here. 
  The Society for Privacy and Confidentiality Resarch exists to support the Journal of Privacy and Confidentiality and connected activties.
copyright: 'Copyright &copy; 2024 Society for Privacy and Confidentiality Research. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created from <a href="https://github.com/swcool">swcool</a>.'
logo: /img/Logo_5_smaller.png
fulllogo: /img/LogoWithName.jpg


# ----------------------- #
#  Stuff about the society#
# ----------------------- #

registration-number: 13709321
registration-date: January 12, 2024
executive:
  - role: President
    name: John M. Abowd
    affiliation: Cornell University
    email: president@journalprivacyconfidentiality.org
  - role: "Treasurer/Secretary" 
    name: Alan F. Karr 
    affiliation: Temple University
    email: treasurer@journalprivacyconfidentiality.org
board:
  - Cynthia Dwork (Harvard University)
  - Jerome P. Reiter (Duke University)
  - Aleksandra Slavković (Penn State University)

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: journal
    icon: newspaper-o
    url: https://journalprivacyconfidentiality.org/
  - title: github
    icon: github
    url: https://github.com/journalprivacyconfidentiality/

navigation:
  - title: Purpose
    url: /#purpose
  - title: Journal
    url: /#journal
  - title: Other
    url: /#tpdp
  - title: About
    url: /#contact
  # Removed Membership entry

collections:
  pages:
    output: true
    permalink: /:name

